export const fundingRoundOrder = {
  ANGEL: { displayName: 'Angel', order: 0 },
  PRE_SEED: { displayName: 'Pre-Seed', order: 1 },
  SEED: { displayName: 'Seed', order: 2 },
  SERIES_A: { displayName: 'Series A', order: 3 },
  SERIES_B: { displayName: 'Series B', order: 4 },
  SERIES_C: { displayName: 'Series C', order: 5 },
  SERIES_D: { displayName: 'Series D', order: 6 },
  SERIES_E: { displayName: 'Series E', order: 7 },
  SERIES_F: { displayName: 'Series F', order: 8 },
  SERIES_G: { displayName: 'Series G', order: 9 },
  SERIES_H: { displayName: 'Series H', order: 10 },
  SERIES_I: { displayName: 'Series I', order: 11 },
  SERIES_J: { displayName: 'Series J', order: 12 },
  SERIES_K: { displayName: 'Series K', order: 13 },
  SERIES_L: { displayName: 'Series L', order: 14 },
  SERIES_M: { displayName: 'Series M', order: 15 },
  SERIES_N: { displayName: 'Series N', order: 16 },
  SERIES_O: { displayName: 'Series O', order: 17 },
  SERIES_P: { displayName: 'Series P', order: 18 },
  SERIES_Q: { displayName: 'Series Q', order: 19 },
  SERIES_R: { displayName: 'Series R', order: 20 },
  SERIES_S: { displayName: 'Series S', order: 21 },
} as any;
